In [216]:
# Import pandas library
import pandas as pd

# Read the CSV file and store it in DataFrame
df = pd.read_csv(
    r"C:\Users\Soham\Desktop\Web Scraping Project\Web Scraping Project\amazon_laptops_data.csv"
)

In [217]:
# Display the first 5 rows of the DataFrame
df.head()

,title,price,rating,brand,ram,storage,color,processor
0,"HP Omnibook 3, Snapdragon X Processor 45 Tops ...",69990.0,NaN,HP,16.0,512.0,Silver,Apple M365
1,"Dell 15 (Previously Inspiron), R5-7520U Proces...",53990.0,NaN,Dell,8.0,512.0,Black,NaN
2,Lenovo V15 G4 AMD Athlon Silver 7120U Laptop 8...,44999.0,NaN,Lenovo,8.0,512.0,Silver,AMD
3,"Acer Smartchoice Aspire One, AMD Ryzen 3-7320U...",42990.0,NaN,Acer,8.0,256.0,Silver,Apple A114
4,Apple 2026 MacBook Neo 13″ Laptop with A18 Pro...,73990.0,NaN,Apple,8.0,256.0,Midnight,Apple A18


In [218]:
# Check the number of rows and columns in the DataFrame
df.shape

(452, 8)

In [219]:
# Check the column names of the DataFrame
df.columns

Index(['title', 'price', 'rating', 'brand', 'ram', 'storage', 'color',
       'processor'],
      dtype='object')

In [220]:
# Step 2: Check basic information about the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   title      452 non-null    object 
 1   price      452 non-null    float64
 2   rating     0 non-null      float64
 3   brand      452 non-null    object 
 4   ram        452 non-null    float64
 5   storage    452 non-null    float64
 6   color      452 non-null    object 
 7   processor  388 non-null    object 
dtypes: float64(4), object(4)
memory usage: 28.4+ KB


In [221]:
# check missing values in the dataset
df.isnull().sum()

title          0
price          0
rating       452
brand          0
ram            0
storage        0
color          0
processor     64
dtype: int64

In [222]:
# clean the price column
df["price"].dtype

dtype('float64')

In [223]:
df["price"].head()

0    69990.0
1    53990.0
2    44999.0
3    42990.0
4    73990.0
Name: price, dtype: float64

In [224]:
# Check all unique values in the price column
df["price"].unique()

array([ 69990.        ,  53990.        ,  44999.        ,  42990.        ,
        73990.        ,  73490.        ,  72990.        ,  67990.        ,
        62490.        , 464490.        ,  35990.        ,  44990.        ,
        83490.        ,  65990.        ,  35670.        ,  25999.        ,
        29990.        ,  49990.        ,  82990.        ,  47990.        ,
        69590.        ,  51400.        ,   9999.        ,  28990.        ,
        70990.        ,  46990.        ,  49450.        ,  84990.        ,
        58790.        ,  87990.        ,  45990.        ,  58990.        ,
        32990.        ,  56890.        ,  69999.        ,  87890.        ,
        55990.        ,  60950.        ,  68700.        , 109990.        ,
        37400.        ,  68699.        , 194990.        , 367900.        ,
        67400.        ,  61000.        ,  42999.        ,  67999.        ,
        48990.        , 129990.        ,  77990.        ,  60160.        ,
       132990.        ,  

In [225]:
# Remove commas from the price values
df["price"] = df["price"].astype(str).str.replace(",", "")

In [226]:
# Convert the price column into numeric values
# Invalid values are converted to NaN
df["price"] = pd.to_numeric(df["price"], errors="coerce")

In [227]:
# Fill missing price values with the mean (average) price
df["price"] = df["price"].fillna(df["price"].mean())

In [228]:
# Check the data type of the price column
df["price"].dtype

dtype('float64')

In [229]:
# Check the number of missing (NaN) values in the price column
df["price"].isnull().sum()

0

In [230]:
# Check all unique values in the rating column
df["rating"].unique()

array([nan])

In [231]:
# Count the frequency of each unique value in the rating column
df["rating"].value_counts()

Series([], Name: count, dtype: int64)

In [232]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   title      452 non-null    object 
 1   price      452 non-null    float64
 2   rating     0 non-null      float64
 3   brand      452 non-null    object 
 4   ram        452 non-null    float64
 5   storage    452 non-null    float64
 6   color      452 non-null    object 
 7   processor  388 non-null    object 
dtypes: float64(4), object(4)
memory usage: 28.4+ KB


In [233]:
# Check all unique values in the rating column
df["rating"].unique()

array([nan])

In [234]:
# Count each unique rating value, including missing (NaN) values
df["rating"].value_counts(dropna=False)

rating
NaN    452
Name: count, dtype: int64

In [235]:
# Then we can decide whether to keep those 7 missing values, remove them, or fill them.
df["rating"].describe()

count    0.0
mean     NaN
std      NaN
min      NaN
25%      NaN
50%      NaN
75%      NaN
max      NaN
Name: rating, dtype: float64

In [236]:
# df["rating"] = df["rating"].fillna(df["rating"].isna().mean() * 100)
df["rating"].isna().sum()


452

In [237]:
# Convert the rating column into numeric values
# Invalid values are converted to NaN
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")

In [238]:
# Fill missing rating values with the median rating
df["rating"] = df["rating"].fillna(df["rating"].median())

In [239]:
# Check all unique values in the rating column
df["rating"].unique()

array([nan])

In [240]:
# Check the count of each rating value, including missing values
df["rating"].value_counts(dropna=False)

rating
NaN    452
Name: count, dtype: int64

In [241]:
# Check all unique values in the brand column
df["brand"].unique()

array(['HP', 'Dell', 'Lenovo', 'Acer', 'Apple', 'ASUS', 'Unknown',
       'JioBook', 'Primebook', 'MSI', 'DELL', 'Alienware', 'Tech', 'NEW',
       'Samsung', 'Certified', 'Microsoft', 'Aspire'], dtype=object)

In [242]:
# Check the number of missing (NaN) values in the brand column
df["brand"].isnull().sum()

0

In [243]:
# Replace lowercase "acer" with "Acer" in the brand column
df["brand"] = df["brand"].replace("acer", "Acer")

In [244]:
# Check the data type of the brand column
df["brand"].dtype

dtype('O')

In [245]:
# Check all unique values in the RAM column
df["ram"].unique()

array([ 16.,   8.,  36.,  12.,   4.,   5.,  24.,   6.,  32., 128.,   7.,
        64.,  48.])

In [246]:
# Convert the RAM column into numeric values
# Invalid values are converted to NaN
df["ram"] = pd.to_numeric(df["ram"], errors="coerce")

In [247]:
# Extract the numeric RAM value from the RAM column
df["ram"] = df["ram"].astype(str).str.extract(r"(\d+)")[0]



In [248]:
import numpy as np

# Replace "RAM" values with NaN (missing values)
df["ram"] = df["ram"].replace("RAM", np.nan)

In [250]:
# Convert RAM values into numeric values
df["ram"] = pd.to_numeric(df["ram"], errors="coerce")

# Fill missing RAM values with the median
df["ram"] = df["ram"].fillna(df["ram"].median())

In [251]:
# Check all unique values in the RAM column
df["ram"].unique()

array([ 16,   8,  36,  12,   4,   5,  24,   6,  32, 128,   7,  64,  48],
      dtype=int64)

In [252]:
df.isna().sum() 

title          0
price          0
rating       452
brand          0
ram            0
storage        0
color          0
processor     64
dtype: int64

In [253]:
df["ram"].dtype

dtype('int64')

In [254]:
# Check all unique values in the storage column
df["storage"].unique()

array([ 512.,  256., 1024., 2048.,   64.,  128.])

In [255]:
# Function to convert storage values into GB
def convert_storage(x):
    # Keep missing values as NaN
    if pd.isna(x):
        return x
    
    # Convert the value to uppercase and remove extra spaces
    x = str(x).upper().strip()
    
    # Convert TB to GB
    if "TB" in x:
        return float(x.replace("TB", "").strip()) * 1024
    
    # Convert GB values to numbers
    if "GB" in x:
        return float(x.replace("GB", "").strip())
    
    # Convert numeric values directly to float
    return float(x)

In [256]:
# Apply the convert_storage function to each value in the storage column
df["storage"] = df["storage"].apply(convert_storage)

In [257]:
# Display the first 5 values of the storage column
print(df["storage"].head())

# Check the data type of the storage column
print(df["storage"].dtype)

0    512.0
1    512.0
2    512.0
3    256.0
4    256.0
Name: storage, dtype: float64
float64


In [258]:
# Check all unique values in the storage column
df["storage"].unique()

array([ 512.,  256., 1024., 2048.,   64.,  128.])

In [259]:
# Check the number of missing (NaN) values in the storage column
df["storage"].isna().sum()

0

In [260]:
# Display all rows where the storage value is missing
df[df["storage"].isna()]

,title,price,rating,brand,ram,storage,color,processor


In [261]:
# Fill missing storage values with the median storage value
df["storage"] = df["storage"].fillna(df["storage"].median())

In [262]:
df["storage"].unique()

array([ 512.,  256., 1024., 2048.,   64.,  128.])

In [263]:
df["storage"].dtype

dtype('float64')

In [264]:
# clean the color
df["color"].unique()

array(['Silver', 'Black', 'Midnight', 'Gray', 'Indigo', 'Blue', 'Grey',
       'gray', 'Sky Blue', 'White', 'Starlight'], dtype=object)

In [265]:
# Import the random module
import random

# List of possible colors for Apple laptops
apple_colors = ["Sky Blue", "Silver", "Starlight", "Midnight"]

# Loop through each row of the DataFrame
for i in df.index:

    # Check if the brand is Apple and the color is missing
    if df.loc[i, "brand"] == "Apple" and pd.isna(df.loc[i, "color"]):

        # Fill the missing color with a random Apple color
        df.loc[i, "color"] = random.choice(apple_colors)

In [266]:
# Check all unique values in the color column
df["color"].unique()

array(['Silver', 'Black', 'Midnight', 'Gray', 'Indigo', 'Blue', 'Grey',
       'gray', 'Sky Blue', 'White', 'Starlight'], dtype=object)

In [267]:
# Count each unique color value, including missing values
df["color"].value_counts(dropna=False)

color
Black        146
Silver       142
Grey          89
Gray          27
Blue          26
Midnight       9
Sky Blue       6
Indigo         3
Starlight      2
gray           1
White          1
Name: count, dtype: int64

In [268]:
# Display all rows where the color value is missing
df[df["color"].isna()]

,title,price,rating,brand,ram,storage,color,processor


In [269]:
# Fill missing color values with "Black"
df["color"] = df["color"].fillna("Black")

In [270]:
df["color"].unique()

array(['Silver', 'Black', 'Midnight', 'Gray', 'Indigo', 'Blue', 'Grey',
       'gray', 'Sky Blue', 'White', 'Starlight'], dtype=object)

In [271]:
# Count each unique processor value, including missing values
df["processor"].value_counts(dropna=False)

processor
Intel          160
Apple M365      80
NaN             64
AMD             58
Apple M5        44
MediaTek        13
Apple A325      10
Apple A18        9
Snapdragon       7
Apple A114       5
Apple A4500      2
Name: count, dtype: int64

In [272]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   title      452 non-null    object 
 1   price      452 non-null    float64
 2   rating     0 non-null      float64
 3   brand      452 non-null    object 
 4   ram        452 non-null    int64  
 5   storage    452 non-null    float64
 6   color      452 non-null    object 
 7   processor  388 non-null    object 
dtypes: float64(3), int64(1), object(4)
memory usage: 28.4+ KB


In [273]:
df.isnull().sum()

title          0
price          0
rating       452
brand          0
ram            0
storage        0
color          0
processor     64
dtype: int64

In [283]:
df.to_csv(
    r"C:\Users\Soham\Desktop\Web Scraping Project\Web Scraping Project\amazon_laptops_cleaned.csv",
    index=False
)
